
export enum ActionType {
    OPEN_SIDEBAR = "OPEN_SIDEBAR",
    FETCH_GETALL_PRODUCT_PENDING = "FETCH_GETALL_PRODUCT_PENDING",
    FETCH_GETALL_PRODUCT_SUCCESS = "FETCH_GETALL_PRODUCT_SUCCESS",
    FETCH_GETALL_PRODUCT_ERROR = "FETCH_GETALL_PRODUCT_ERROR",

    FETCH_ADD_PRODUCT_PENDING = "FETCH_ADD_PRODUCT_PENDING",
    FETCH_ADD_PRODUCT_SUCCESS = "FETCH_ADD_PRODUCT_SUCCESS",
    FETCH_ADD_PRODUCT_ERROR = "FETCH_ADD_PRODUCT_ERROR",

    FETCH_ADD_CATEGORY_PENDING = "FETCH_ADD_CATEGORY_PENDING",
    FETCH_ADD_CATEGORY_SUCCESS = "FETCH_ADD_CATEGORY_SUCCESS",
    FETCH_ADD_CATEGORY_ERROR = "FETCH_ADD_CATEGORY_ERROR",

    FETCH_GETALL_CATEGORY_PENDING = "FETCH_GETALL_CATEGORY_PENDING",
    FETCH_GETALL_CATEGORY_SUCCESS = "FETCH_GETALL_CATEGORY_SUCCESS",
    FETCH_GETALL_CATEGORY_ERROR = "FETCH_GETALL_CATEGORY_ERROR",

    FETCH_DELETE_PRODUCT_PENDING = "FETCH_DELETE_PRODUCT_PENDING",
    FETCH_DELETE_PRODUCT_SUCCESS = "FETCH_DELETE_PRODUCT_SUCCESS",
    FETCH_DELETE_PRODUCT_ERROR = "FETCH_DELETE_PRODUCT_ERROR",

    FETCH_DELETE_CATEGORY_PENDING = "FETCH_DELETE_CATEGORY_PENDING",
    FETCH_DELETE_CATEGORY_SUCCESS = "FETCH_DELETE_CATEGORY_SUCCESS",
    FETCH_DELETE_CATEGORY_ERROR = "FETCH_DELETE_CATEGORY_ERROR",

    FETCH_UPDATE_PRODUCT_PENDING = "FETCH_UPDATE_PRODUCT_PENDING",
    FETCH_UPDATE_PRODUCT_SUCCESS = "FETCH_UPDATE_PRODUCT_SUCCESS",
    FETCH_UPDATE_PRODUCT_ERROR = "FETCH_UPDATE_PRODUCT_ERROR",

    FETCH_UPDATE_CATEGORY_PENDING = "FETCH_UPDATE_CATEGORY_PENDING",
    FETCH_UPDATE_CATEGORY_SUCCESS = "FETCH_UPDATE_CATEGORY_SUCCESS",
    FETCH_UPDATE_CATEGORY_ERROR = "FETCH_UPDATE_CATEGORY_ERROR",

    FETCH_LOGIN_PENDING = "FETCH_LOGIN_PENDING",
    FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS",
    FETCH_LOGIN_ERROR = "FETCH_LOGIN_ERROR",

    FETCH_CHECK_LOGIN_PENDING = "FETCH_CHECK_LOGIN_PENDING",
    FETCH_CHECK_LOGIN_SUCCESS = "FETCH_CHECK_LOGIN_SUCCESS",
    FETCH_CHECK_LOGIN_ERROR = "FETCH_CHECK_LOGIN_ERROR",

    FETCH_LOGOUT_PENDING = "FETCH_LOGOUT_PENDING",
    FETCH_LOGOUT_SUCCESS = "FETCH_LOGOUT_SUCCESS",
    FETCH_LOGOUT_ERROR = "FETCH_LOGOUT_ERROR",

    HANLDE_PAGING_CATEGORIES = "HANLDE_PAGING_CATEGORIES",
    HANLDE_PAGING_PRODUCTS = "HANLDE_PAGING_PRODUCTS",

    OPEN_MODAL_DELETE_PRODUCT = "OPEN_MODAL_DELETE_PRODUCT",
    OPEN_MODAL_UPDATE_PRODUCT = "OPEN_MODAL_UPDATE_PRODUCT",
    OPEN_MODAL_ADD_NEW_CATEGORY = "OPEN_MODAL_ADD_NEW_CATEGORY",
    OPEN_MODAL_DELETE_CATEGORY = "OPEN_MODAL_DELETE_CATEGORY",
    OPEN_MODAL_UPDATE_CATEGORY = "OPEN_MODAL_UPDATE_CATEGORY",
    // HANLDE_MODAL_DELETE = "HANLDE_MODAL_DELETE",
}

export interface sideBarAction {
    type: ActionType.OPEN_SIDEBAR
    payload: boolean
}

export interface fetchProductPendingAction {
    type: ActionType.FETCH_GETALL_PRODUCT_PENDING
    payload: boolean
}
export enum TypeDeleteModal {
    product,
    category,
}
